stages:
    - build
    - test

setup docker build:
    stage: build
    script:
    - docker info
    - docker-compose -f docker-compose-test.yml build

run tests:
    stage: test
    script:
    - docker-compose -f docker-compose-test.yml up speedtest-dev
    after_script:
    - docker-compose -f docker-compose-test.yml down
