stages:
    - build_image

before_script:
  - docker info

run_image:
    stage: run_image
    script:
    - docker-compose build
    - docker-compose up -d
    after_script:
    - docker-compose down

