# Only runs commands on production servers via runner shell, uses tag specified in GitLab GUI

stages:
    - build
    - test
    - clean
    - exe_1
    - exe_2
    - exe_3
    - deploy-prod

setup docker build:
    stage: build
    tags:
    - lab_docker
    script:
    - ls -R
    - docker info
    - docker-compose -f docker-compose-test.yml build
    - docker image ls

run tests:
    stage: test
    tags:
    - lab_docker
    script:
    - docker-compose -f docker-compose-test.yml up -d speedsql-dev
    - docker-compose -f docker-compose-test.yml run speedtest-dev

clean up test env:
    stage: clean
    tags:
    - lab_docker
    script:
    - docker-compose -f docker-compose-test.yml down --rmi local --volumes --remove-orphans
    when: always

code complexity:
    stage: clean
    tags:
    - lab_docker
    script:
    - radon cc -a .

install py modules:
    stage: exe_1
    tags:
    - win
    script:
    - pip install -r speed/requirements.txt
    artifacts:
      name: "%CI_JOB_NAME%-%CI_COMMIT_REF_NAME%"
      untracked: true

complie exe:
    stage: exe_2
    tags:
    - win
    script:
    - dir
    - python -m nuitka speed/speed_test.py --follow-imports --standalone --show-progress --remove-output --python-flag=no_site  --assume-yes-for-downloads
    - dir
    artifacts:
      name: "%CI_JOB_NAME%-%CI_COMMIT_REF_NAME%"
      untracked: true # Adds all untracked files

remove py modules:
    stage: exe_3
    tags:
    - win
    script:
    - pip uninstall -r speed/requirements.txt

deploy production:
    stage: deploy-prod
    tags:
    - lab_docker
    environment:
      name: production
      on_stop: stop production
    when: manual
    allow_failure: false
    only:
      - master
    script:
      - ls -R
      - docker image ls
      - docker-compose -f docker-compose-deploy.yml down --rmi local --remove-orphans
      - docker-compose -f docker-compose-deploy.yml rm -f
      - docker-compose -f docker-compose-deploy.yml build
      - docker tag autobot:latest autobot:$CI_COMMIT_SHA
      - docker-compose -f docker-compose-deploy.yml up -d
      - docker image ls

stop production:
    stage: deploy-prod
    tags:
    - lab_docker
    when: manual
    only:
      - master
    environment:
      name: production
      action: stop
    script:
      - docker-compose -f docker-compose-deploy.yml down --rmi local --remove-orphans
