version: '3'
services:
  speedtest-dev:
    networks:
      - speed-test
    restart: on-failure
    image: speedtest-dev
    depends_on:
      - speedsql-dev
    build:
      context: .
      dockerfile: speed/Dockerfile
    working_dir: /speed
    entrypoint: python
    command: -m pytest --cov -v -s
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb

  webgui-dev:
    networks:
      - speed-test
    depends_on:
      - speedsql-dev
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb
    ports:
     - "5001:5000"

  speedsql-dev:
    networks:
      - speed-test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: speed_user
      POSTGRES_PASSWORD: speed_pass
      POSTGRES_DB: speeddb
    volumes:
      - speed-data-vol-dev:/var/lib/postgresql/data

  speedtest-dev-coverage:
    networks:
      - speed-test
    depends_on:
      - speedsql-dev
    image: speedtest-dev
    working_dir: /speed
    entrypoint: python
    command: -m pytest --cov-report:/coverage/
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb
    volumes:
      - speed-coverage-report:/coverage

volumes:
  speed-data-vol-dev:
  speed-coverage-report:

networks:
  speed-test:
