version: '3'
services:
  speedtest:
    restart: on-failure
    depends_on:
      - speedsql
    build:
      context: .
      dockerfile: speed/Dockerfile
    working_dir: /speed
    entrypoint: python
    command: /speed/speed_check.py -g --debug
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb

#  logging:
#    driver: syslog
#    options:
#      syslog-address: "tcp://192.168.0.42:123"

  webgui:
    depends_on:
      - speedsql
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb
    ports:
      - "5000:5000"

  speedsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: speed_user
      POSTGRES_PASSWORD: speed_pass
      POSTGRES_DB: speeddb
    volumes:
      - speed-data-vol:/var/lib/postgresql/data

  pgadmin:
  # Heavy weight GUI for production
    depends_on:
      - speedsql
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.local
      PGADMIN_DEFAULT_PASSWORD: changeme

  #docker run -p 443:443 \
  #-v "/private/var/lib/pgadmin:/var/lib/pgadmin" \
  #-v "/path/to/certificate.cert:/certs/server.cert" \
  #-v "/path/to/certificate.key:/certs/server.key" \
  #-e "PGADMIN_DEFAULT_EMAIL=user@domain.com" \
  #-e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" \
  #-e "PGADMIN_ENABLE_TLS=True" \
  #-d dpage/pgadmin4



volumes:
  speed-data-vol: