version: '3'
services:
  speedtest-dev:
    depends_on:
      - speedsql-dev
    build:
      context: .
      dockerfile: speed/Dockerfile
    environment:
      - SQL_NAME=speedsql-dev
    entrypoint: python
    command: -m pytest

  webgui-dev:
    depends_on:
      - speedsql-dev
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      - SQL_NAME=speedsql-dev
    ports:
     - "5001:5000"


  speedsql-dev:
    image: postgres
    restart: always
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: speed_user
      POSTGRES_PASSWORD: speed_pass

  adminer-dev:
    image: adminer
    restart: always
    ports:
      - 8082:8080