version: '3'
services:
  speedtest-dev:
    restart: on-failure
    depends_on:
      - speedsql-dev
    build:
      context: .
      dockerfile: speed/Dockerfile
    working_dir: /speed
    entrypoint: python
    command: -m pytest --cov
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb


  webgui-dev:
    depends_on:
      - speedsql-dev
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      SQL_HOSTNAME: speedsql
      SQL_USERNAME: speed_user
      SQL_PASSWORD: speed_pass
      SQL_PORT: 5432
      SQL_DB: speeddb
    ports:
     - "5001:5000"

  speedsql-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: speed_user
      POSTGRES_PASSWORD: speed_pass
      POSTGRES_DB: speeddb
    volumes:
      - speed-data-vol-dev:/var/lib/postgresql/data

volumes:
  speed-data-vol-dev: