FROM python:3
ADD graph-web.py /
ADD . /Database
RUN pip install --upgrade pip R
RUN pip install Flask
RUN pip install pygal
RUN pip install SQLAlchemy
RUN pip install psycopg2
RUN ls
EXPOSE 5000
WORKDIR /WebGUI
ENTRYPOINT [ "python"]
CMD ["./graph-web.py"]