version: '3'
services:
  speedtest:
    restart: on-failure
    depends_on:
      - speedsql
    build:
      context: .
      dockerfile: speed/Dockerfile
    environment:
      - SQL_HOSTNAME=speedsql

  webgui:
    depends_on:
      - speedsql
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      - SQL_HOSTNAME=speedsql
    ports:
     - "5000:5000"

  speedsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: speed_user
      POSTGRES_PASSWORD: speed_pass
      POSTGRES_DB: speeddb
    volumes:
      - speed-data-vol:/var/lib/postgresql/data

  pgadmin4:
    depends_on:
      - speedsql
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.local
      PGADMIN_DEFAULT_PASSWORD: changeme

volumes:
  speed-data-vol: