FROM python:3
ADD test-speed.py /
ADD Database /Database
RUN pip install prettytable
RUN pip install speedtest-cli
RUN pip install SQLAlchemy
RUN pip install psycopg2
ENTRYPOINT [ "python"]
CMD ["./test-speed.py","-g", "--debug"]