version: '3'
services:
  speedtest:
    build:
      context: .
      dockerfile: speed/Dockerfile

  webgui:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
     - "5000:5000"


  speedsql:
    image: postgres
    restart: always
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: speed_user
      POSTGRES_PASSWORD: speed_pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080