FROM python:3.6-alpine

RUN apk add openssh
RUN mkdir /root/.ssh && chmod 700 /root/.ssh
RUN echo "root:changeme" | chpasswd
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN ssh-keygen -A

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
ADD /speed /
ADD /Database /Database
RUN pip install -r requirements.txt
RUN ls

WORKDIR /
EXPOSE 22
CMD [ "/usr/sbin/sshd", "-D", "-e"]